version: '3'
services:
  db-inventory:
    container_name: db-inventory
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-orders:
    container_name: db-orders
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-products:
    container_name: db-products
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - prometheus
    environment:
      GF_SECURITY:ADMIN_PASSWORD: admin
      GF_SECURITY:ADMIN_USER: admin
    depends_on:
      - prometheus

  db-keycloak:
    container_name: db-keycloak
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db-keycloak
      DB_PORT: 5433
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT:HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

