version: '3'
services:
  db-inventory:
    container_name: db-inventory
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-orders:
    container_name: db-orders
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-products:
    container_name: db-products
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - prometheus
    environment:
      GF_SECURITY:ADMIN_PASSWORD: admin
      GF_SECURITY:ADMIN_USER: admin
    depends_on:
      - prometheus