version: '3'
services:
  db-inventory:
    container_name: db-inventory
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-orders:
    container_name: db-orders
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-products:
    container_name: db-products
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433